// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZLc57xssJv9tsF_Lb58rf9SVzuHFgJbw',
    appId: '1:163564066703:web:ca76e1f418ec5e3ab49dfa',
    messagingSenderId: '163564066703',
    projectId: 'cocktails-9cc9a',
    authDomain: 'cocktails-9cc9a.firebaseapp.com',
    databaseURL: 'https://cocktails-9cc9a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cocktails-9cc9a.appspot.com',
    measurementId: 'G-S7XC989NZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzlrQvEN0widT9jcZb1mhgTJIuaLhEzYg',
    appId: '1:163564066703:android:e110111d80876324b49dfa',
    messagingSenderId: '163564066703',
    projectId: 'cocktails-9cc9a',
    databaseURL: 'https://cocktails-9cc9a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cocktails-9cc9a.appspot.com',
  );
}
